[project]
name = "jiny-ai-agent"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "jiny314", email = "ddongl8eeeee@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "geopandas>=1.1.4",
]

[project.scripts]
jiny-ai-agent = "jiny_ai_agent:main"

[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"
